
package com.blueice.mywebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceFuncService", targetNamespace = "http://mywebservice.blueice.com/", wsdlLocation = "http://192.168.0.95:9999/WebService?wsdl")
public class WebServiceFuncService
    extends Service
{

    private final static URL WEBSERVICEFUNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEFUNCSERVICE_EXCEPTION;
    private final static QName WEBSERVICEFUNCSERVICE_QNAME = new QName("http://mywebservice.blueice.com/", "WebServiceFuncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.95:7418/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEFUNCSERVICE_WSDL_LOCATION = url;
        WEBSERVICEFUNCSERVICE_EXCEPTION = e;
    }

    public WebServiceFuncService() {
        super(__getWsdlLocation(), WEBSERVICEFUNCSERVICE_QNAME);
    }

    public WebServiceFuncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEFUNCSERVICE_QNAME, features);
    }

    public WebServiceFuncService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEFUNCSERVICE_QNAME);
    }

    public WebServiceFuncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEFUNCSERVICE_QNAME, features);
    }

    public WebServiceFuncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceFuncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceFunc
     */
    @WebEndpoint(name = "WebServiceFuncPort")
    public WebServiceFunc getWebServiceFuncPort() {
        return super.getPort(new QName("http://mywebservice.blueice.com/", "WebServiceFuncPort"), WebServiceFunc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceFunc
     */
    @WebEndpoint(name = "WebServiceFuncPort")
    public WebServiceFunc getWebServiceFuncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mywebservice.blueice.com/", "WebServiceFuncPort"), WebServiceFunc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEFUNCSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEFUNCSERVICE_EXCEPTION;
        }
        return WEBSERVICEFUNCSERVICE_WSDL_LOCATION;
    }

}
