
package com.blueice.mywebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceFunc", targetNamespace = "http://mywebservice.blueice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceFunc {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.blueice.mywebservice.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserById", targetNamespace = "http://mywebservice.blueice.com/", className = "com.blueice.mywebservice.FindUserById")
    @ResponseWrapper(localName = "findUserByIdResponse", targetNamespace = "http://mywebservice.blueice.com/", className = "com.blueice.mywebservice.FindUserByIdResponse")
    @Action(input = "http://mywebservice.blueice.com/WebServiceFunc/findUserByIdRequest", output = "http://mywebservice.blueice.com/WebServiceFunc/findUserByIdResponse")
    public User findUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://mywebservice.blueice.com/", className = "com.blueice.mywebservice.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://mywebservice.blueice.com/", className = "com.blueice.mywebservice.TestResponse")
    @Action(input = "http://mywebservice.blueice.com/WebServiceFunc/testRequest", output = "http://mywebservice.blueice.com/WebServiceFunc/testResponse")
    public void test();

}
